// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbnyijhnomuehhmfqqxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRibnlpamhub211ZWhobWZxcXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzQ2NjgsImV4cCI6MjA2NjU1MDY2OH0.oq_SYTxa1Ln-zGJW_S8GfEAZjYy9QWaNTQ4Gk-nVd2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);